/**
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.tptp.ide;

import it.unibz.inf.tptp.ide.AbstractTPTPIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class TPTPIdeModule extends AbstractTPTPIdeModule {
}
