/**
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.tptp.parser;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cnf equality</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibz.inf.tptp.parser.Cnf_equality#getExpL <em>Exp L</em>}</li>
 *   <li>{@link it.unibz.inf.tptp.parser.Cnf_equality#getEq <em>Eq</em>}</li>
 *   <li>{@link it.unibz.inf.tptp.parser.Cnf_equality#getExpR <em>Exp R</em>}</li>
 * </ul>
 *
 * @see it.unibz.inf.tptp.parser.ParserPackage#getCnf_equality()
 * @model
 * @generated
 */
public interface Cnf_equality extends EObject
{
  /**
   * Returns the value of the '<em><b>Exp L</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exp L</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp L</em>' containment reference.
   * @see #setExpL(Cnf_expression)
   * @see it.unibz.inf.tptp.parser.ParserPackage#getCnf_equality_ExpL()
   * @model containment="true"
   * @generated
   */
  Cnf_expression getExpL();

  /**
   * Sets the value of the '{@link it.unibz.inf.tptp.parser.Cnf_equality#getExpL <em>Exp L</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp L</em>' containment reference.
   * @see #getExpL()
   * @generated
   */
  void setExpL(Cnf_expression value);

  /**
   * Returns the value of the '<em><b>Eq</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Eq</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Eq</em>' attribute.
   * @see #setEq(String)
   * @see it.unibz.inf.tptp.parser.ParserPackage#getCnf_equality_Eq()
   * @model
   * @generated
   */
  String getEq();

  /**
   * Sets the value of the '{@link it.unibz.inf.tptp.parser.Cnf_equality#getEq <em>Eq</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Eq</em>' attribute.
   * @see #getEq()
   * @generated
   */
  void setEq(String value);

  /**
   * Returns the value of the '<em><b>Exp R</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exp R</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp R</em>' containment reference.
   * @see #setExpR(Cnf_expression)
   * @see it.unibz.inf.tptp.parser.ParserPackage#getCnf_equality_ExpR()
   * @model containment="true"
   * @generated
   */
  Cnf_expression getExpR();

  /**
   * Sets the value of the '{@link it.unibz.inf.tptp.parser.Cnf_equality#getExpR <em>Exp R</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp R</em>' containment reference.
   * @see #getExpR()
   * @generated
   */
  void setExpR(Cnf_expression value);

} // Cnf_equality
