/**
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.tptp.parser;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cnf expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibz.inf.tptp.parser.Cnf_expression#getCnf_exp <em>Cnf exp</em>}</li>
 *   <li>{@link it.unibz.inf.tptp.parser.Cnf_expression#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see it.unibz.inf.tptp.parser.ParserPackage#getCnf_expression()
 * @model
 * @generated
 */
public interface Cnf_expression extends EObject
{
  /**
   * Returns the value of the '<em><b>Cnf exp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cnf exp</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cnf exp</em>' attribute.
   * @see #setCnf_exp(String)
   * @see it.unibz.inf.tptp.parser.ParserPackage#getCnf_expression_Cnf_exp()
   * @model
   * @generated
   */
  String getCnf_exp();

  /**
   * Sets the value of the '{@link it.unibz.inf.tptp.parser.Cnf_expression#getCnf_exp <em>Cnf exp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cnf exp</em>' attribute.
   * @see #getCnf_exp()
   * @generated
   */
  void setCnf_exp(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see it.unibz.inf.tptp.parser.ParserPackage#getCnf_expression_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link it.unibz.inf.tptp.parser.Cnf_expression#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // Cnf_expression
