/**
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.tptp.parser;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fof var</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unibz.inf.tptp.parser.ParserPackage#getFof_var()
 * @model
 * @generated
 */
public interface Fof_var extends Fof_atom
{
} // Fof_var
