/**
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.tptp.parser;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>fof constant</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibz.inf.tptp.parser.fof_constant#getFof_param <em>Fof param</em>}</li>
 * </ul>
 *
 * @see it.unibz.inf.tptp.parser.ParserPackage#getfof_constant()
 * @model
 * @generated
 */
public interface fof_constant extends fof_atom
{
  /**
   * Returns the value of the '<em><b>Fof param</b></em>' containment reference list.
   * The list contents are of type {@link it.unibz.inf.tptp.parser.fof_atom}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fof param</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fof param</em>' containment reference list.
   * @see it.unibz.inf.tptp.parser.ParserPackage#getfof_constant_Fof_param()
   * @model containment="true"
   * @generated
   */
  EList<fof_atom> getFof_param();

} // fof_constant
