/**
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.tptp.parser;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Include</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibz.inf.tptp.parser.Include#getPath <em>Path</em>}</li>
 * </ul>
 *
 * @see it.unibz.inf.tptp.parser.ParserPackage#getInclude()
 * @model
 * @generated
 */
public interface Include extends Fof_input, Tff_input, Cnf_input, Thf_input
{
  /**
   * Returns the value of the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Path</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Path</em>' attribute.
   * @see #setPath(String)
   * @see it.unibz.inf.tptp.parser.ParserPackage#getInclude_Path()
   * @model
   * @generated
   */
  String getPath();

  /**
   * Sets the value of the '{@link it.unibz.inf.tptp.parser.Include#getPath <em>Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Path</em>' attribute.
   * @see #getPath()
   * @generated
   */
  void setPath(String value);

} // Include
