/**
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.tptp.parser;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tff atom</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unibz.inf.tptp.parser.ParserPackage#getTff_atom()
 * @model
 * @generated
 */
public interface Tff_atom extends EObject
{
} // Tff_atom
