/**
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.tptp.parser;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Thf var</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unibz.inf.tptp.parser.ParserPackage#getThf_var()
 * @model
 * @generated
 */
public interface Thf_var extends Thf_atom
{
} // Thf_var
