/**
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.tptp.parser;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>fof var</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unibz.inf.tptp.parser.ParserPackage#getfof_var()
 * @model
 * @generated
 */
public interface fof_var extends fof_atom
{
} // fof_var
