/**
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.tptp.parser;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>tff root</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibz.inf.tptp.parser.tff_root#getName <em>Name</em>}</li>
 *   <li>{@link it.unibz.inf.tptp.parser.tff_root#getFormula_role <em>Formula role</em>}</li>
 *   <li>{@link it.unibz.inf.tptp.parser.tff_root#getExp <em>Exp</em>}</li>
 *   <li>{@link it.unibz.inf.tptp.parser.tff_root#getDef <em>Def</em>}</li>
 * </ul>
 *
 * @see it.unibz.inf.tptp.parser.ParserPackage#gettff_root()
 * @model
 * @generated
 */
public interface tff_root extends tff_input
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see it.unibz.inf.tptp.parser.ParserPackage#gettff_root_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link it.unibz.inf.tptp.parser.tff_root#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Formula role</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Formula role</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Formula role</em>' attribute.
   * @see #setFormula_role(String)
   * @see it.unibz.inf.tptp.parser.ParserPackage#gettff_root_Formula_role()
   * @model
   * @generated
   */
  String getFormula_role();

  /**
   * Sets the value of the '{@link it.unibz.inf.tptp.parser.tff_root#getFormula_role <em>Formula role</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Formula role</em>' attribute.
   * @see #getFormula_role()
   * @generated
   */
  void setFormula_role(String value);

  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exp</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(tff_expression)
   * @see it.unibz.inf.tptp.parser.ParserPackage#gettff_root_Exp()
   * @model containment="true"
   * @generated
   */
  tff_expression getExp();

  /**
   * Sets the value of the '{@link it.unibz.inf.tptp.parser.tff_root#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(tff_expression value);

  /**
   * Returns the value of the '<em><b>Def</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Def</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Def</em>' containment reference.
   * @see #setDef(tff_formula_type_definition)
   * @see it.unibz.inf.tptp.parser.ParserPackage#gettff_root_Def()
   * @model containment="true"
   * @generated
   */
  tff_formula_type_definition getDef();

  /**
   * Sets the value of the '{@link it.unibz.inf.tptp.parser.tff_root#getDef <em>Def</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Def</em>' containment reference.
   * @see #getDef()
   * @generated
   */
  void setDef(tff_formula_type_definition value);

} // tff_root
