/**
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.tptp.parser;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>tff var declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibz.inf.tptp.parser.tff_var_declaration#getVar <em>Var</em>}</li>
 *   <li>{@link it.unibz.inf.tptp.parser.tff_var_declaration#getVartype <em>Vartype</em>}</li>
 * </ul>
 *
 * @see it.unibz.inf.tptp.parser.ParserPackage#gettff_var_declaration()
 * @model
 * @generated
 */
public interface tff_var_declaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' containment reference.
   * @see #setVar(tff_var)
   * @see it.unibz.inf.tptp.parser.ParserPackage#gettff_var_declaration_Var()
   * @model containment="true"
   * @generated
   */
  tff_var getVar();

  /**
   * Sets the value of the '{@link it.unibz.inf.tptp.parser.tff_var_declaration#getVar <em>Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' containment reference.
   * @see #getVar()
   * @generated
   */
  void setVar(tff_var value);

  /**
   * Returns the value of the '<em><b>Vartype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Vartype</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vartype</em>' containment reference.
   * @see #setVartype(tff_type_expression)
   * @see it.unibz.inf.tptp.parser.ParserPackage#gettff_var_declaration_Vartype()
   * @model containment="true"
   * @generated
   */
  tff_type_expression getVartype();

  /**
   * Sets the value of the '{@link it.unibz.inf.tptp.parser.tff_var_declaration#getVartype <em>Vartype</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vartype</em>' containment reference.
   * @see #getVartype()
   * @generated
   */
  void setVartype(tff_type_expression value);

} // tff_var_declaration
