/**
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.tptp.parser;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>thf constant</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibz.inf.tptp.parser.thf_constant#getThf_param <em>Thf param</em>}</li>
 * </ul>
 *
 * @see it.unibz.inf.tptp.parser.ParserPackage#getthf_constant()
 * @model
 * @generated
 */
public interface thf_constant extends thf_atom
{
  /**
   * Returns the value of the '<em><b>Thf param</b></em>' containment reference list.
   * The list contents are of type {@link it.unibz.inf.tptp.parser.thf_atom}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Thf param</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Thf param</em>' containment reference list.
   * @see it.unibz.inf.tptp.parser.ParserPackage#getthf_constant_Thf_param()
   * @model containment="true"
   * @generated
   */
  EList<thf_atom> getThf_param();

} // thf_constant
