/**
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.tptp.parser;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>thf type atom</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unibz.inf.tptp.parser.ParserPackage#getthf_type_atom()
 * @model
 * @generated
 */
public interface thf_type_atom extends thf_type_expression
{
} // thf_type_atom
