/**
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.tptp;

import it.unibz.inf.tptp.TPTPStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TPTPStandaloneSetup extends TPTPStandaloneSetupGenerated {
  public static void doSetup() {
    new TPTPStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
