/*
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.tptp


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TPTPRuntimeModule extends AbstractTPTPRuntimeModule {
}
